function instructions(w)
    msg = [...
        '1. Prep: Look at the blue cross.' ...
        ' A dot is about to appear.\n\n' ...
        '2. Look: Look at the dot inside the dot and remember that spot'...
        ' until it goes away.\n\n' ...
        '3. Wait: Look at the yellow cross in the center.\n\n' ...
        '4. Recall: When the yellow cross goes away. ' ...
        'Look back to where you saw the dot until ... \n\n' ...
        '5. Relax: Look at the white cross in the center when it comes back.\n\n'...
        'NOTE: you do not need to remember the images for this task ' ...
        'but you may be asked about them later'];
    DrawFormattedText(w, msg, 0, 0, [255 255 255]);
    Screen('Flip',w);
    WaitSecs(.5);
    KbWait();
    
    img = imread('img/instruction/overview.png');
    tex = Screen('MakeTexture',w, img);
    Screen('DrawTexture',w, tex);
    Screen('Flip',w);
    WaitSecs(.5);
    KbWait();
    
end